version: "3.9"

services:
  web:
    build: .
    user: "node:node"
    environment:
      - APP_PORT=${APP_PORT:-3000}
    volumes:
      - "./app:/usr/src/app"
    ports:
      - "3000:3000"
    env_file:
      - ./app/config/.env  

  postgres:
    image: postgres:latest
    container_name: postgres-container
    env_file:
      - ./app/config/.env  
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    env_file:
      - ./app/config/.env  
    ports:
      - "5050:80"
    depends_on:
      - postgres
