name: React to Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changes_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Adicione aqui os passos adicionais que você deseja executar
